server:
  port: 5050
  servlet:
    context-path: /shop
spring:
  application:
    name: HelloShoesBackEnd
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      password: nipun1234
      jdbc-url: jdbc:mysql://location:3306/hello_Shoes?creatDatabaseIfNoteExist=true
      username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    show-sql: true

